# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 347dd841cff55bc1d499eb78ce7c25751625a7dfc47c4054035cdebda5f04f1183fede729aa56fbab0df7b6f391b633722da4b56af65f050acc1dbae8f3d6091

test:
  secret_key_base: 624c235523aaa5f97608b14188ad26cddcdc7d287225a3dffaae3da9ffff5e2aecc70899413488d326b3efa77803a10f935f8a949f3f5a79d10b9e084a38ba00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
